package Entity;
// Generated 9 nov. 2019 21:08:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dept generated by hbm2java
 */
@Entity
@Table(name="dept"
    ,catalog="jeetp"
)
public class Dept  implements java.io.Serializable {


     private String deptno;
     private String dname;
     private Set<Emp> emps = new HashSet<Emp>(0);

    public Dept() {
    }

	
    public Dept(String deptno) {
        this.deptno = deptno;
    }
    public Dept(String deptno, String dname, Set<Emp> emps) {
       this.deptno = deptno;
       this.dname = dname;
       this.emps = emps;
    }
   
     @Id 

    
    @Column(name="deptno", unique=true, nullable=false, length=6)
    public String getDeptno() {
        return this.deptno;
    }
    
    public void setDeptno(String deptno) {
        this.deptno = deptno;
    }

    
    @Column(name="dname", length=14)
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dept")
    public Set<Emp> getEmps() {
        return this.emps;
    }
    
    public void setEmps(Set<Emp> emps) {
        this.emps = emps;
    }




}


