package Entity;
// Generated 9 nov. 2019 21:08:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Emp generated by hbm2java
 */
@Entity
@Table(name="emp"
    ,catalog="jeetp"
)
public class Emp  implements java.io.Serializable {


     private String empno;
     private Dept dept;
     private String ename;
     private BigDecimal sal;

    public Emp() {
    }

	
    public Emp(String empno) {
        this.empno = empno;
    }
    public Emp(String empno, Dept dept, String ename, BigDecimal sal) {
       this.empno = empno;
       this.dept = dept;
       this.ename = ename;
       this.sal = sal;
    }
   
     @Id 

    
    @Column(name="empno", unique=true, nullable=false, length=25)
    public String getEmpno() {
        return this.empno;
    }
    
    public void setEmpno(String empno) {
        this.empno = empno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="deptno")
    public Dept getDept() {
        return this.dept;
    }
    
    public void setDept(Dept dept) {
        this.dept = dept;
    }

    
    @Column(name="ename", length=10)
    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }

    
    @Column(name="sal", precision=7)
    public BigDecimal getSal() {
        return this.sal;
    }
    
    public void setSal(BigDecimal sal) {
        this.sal = sal;
    }




}


